#!/bin/bash
# Daily refresh — news + events + predictions + git push.
# Runs autonomously via launchd at 18:30 IST weekdays (post-market-close).
# See configs/com.shree-ganesh.daily-refresh.plist for the schedule.
#
# What this script does:
#   1) Fetch news (RSS + per-symbol) and corporate events
#   2) Rebuild news_event_features.parquet (5d/7d/15d windows, stock + industry)
#   3) Re-run find_180d_frontier_honest.py (calibrated 2x scoring)
#   4) Re-run find_multibagger_targets.py (cross-validation pipeline)
#   5) Write live_predictions/YYYY-MM-DD.json with today's cross-validated basket
#   6) Run devils_advocate.py if it has been > 7 days since last run
#   7) git add + commit + push to GitHub
#
# Constitution-binding:
#   - Skips Phase-2-blocked steps (apply_adjustments still pending)
#   - Does NOT auto-trade; only writes the prediction artifact for review
#   - Logs everything to logs/daily_refresh_YYYYMMDD_HHMM.log

set -uo pipefail

ROOT="/Users/abhinavs./Documents/Zoom"
cd "$ROOT" || exit 1

DATE_TAG=$(date +%Y%m%d_%H%M)
TODAY=$(date +%Y-%m-%d)
LOG="$ROOT/logs/daily_refresh_${DATE_TAG}.log"
mkdir -p "$ROOT/logs" "$ROOT/live_predictions"

PY="/usr/bin/python3"
export PYTHONPATH="$ROOT"
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/homebrew/bin:$PATH"

log() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$LOG"; }

run_step() {
    local name="$1"; shift
    log ">>> $name"
    if "$@" >> "$LOG" 2>&1; then
        log "<<< OK    $name"
        return 0
    else
        local rc=$?
        log "<<< FAIL($rc) $name (continuing)"
        return $rc
    fi
}

log "============================================="
log "Daily refresh start — $(date)"
log "============================================="

# --- Step 1: fetch news + events ---
run_step "fetch_news_rss" $PY src/agentic/fetch_news_rss.py
run_step "fetch_news_per_symbol" $PY src/agentic/fetch_news_per_symbol.py
run_step "score_sentiment" $PY src/agentic/score_sentiment.py

# --- Step 2: rebuild news/event features ---
run_step "build_news_event_features" $PY src/agentic/build_news_event_features.py

# --- Step 3: re-run honest 180d frontier ---
run_step "find_180d_frontier_honest" $PY src/agentic/find_180d_frontier_honest.py

# --- Step 4: re-run multibagger pipeline ---
run_step "find_multibagger_targets" $PY src/agentic/find_multibagger_targets.py

# --- Step 5: write today's live prediction ---
run_step "write_live_prediction" $PY src/agentic/write_live_prediction.py --date "$TODAY"

# --- Step 6: devils_advocate weekly (only on Sundays for the full audit) ---
if [ "$(date +%u)" = "7" ]; then
    run_step "devils_advocate (weekly Sunday)" $PY src/agentic/devils_advocate.py
    run_step "backtest_news_features (weekly Sunday)" $PY src/agentic/backtest_news_features.py
fi

# --- Step 7: git add + commit + push ---
log ">>> git operations"
{
    git add live_predictions/ data/derived/news_event_features.parquet \
            data/derived/180d_today_predictions.parquet \
            data/derived/multibagger_today_predictions.parquet \
            reports/180d_honest_frontier.md \
            reports/multibagger_targets.md \
            reports/devils_advocate_audit.md \
            reports/news_backtest_*.md 2>/dev/null

    if git diff --cached --quiet; then
        log "<<< git: nothing to commit"
    else
        git -c user.name="abhinavs" -c user.email="abhinavs@users.noreply.github.com" \
            commit -m "Daily refresh ${TODAY}

Auto-generated by daily_refresh.sh at $(date +'%H:%M %Z'). Includes:
- Fresh news + corporate events (5d/7d/15d windows)
- Re-run of find_180d_frontier_honest.py
- Re-run of find_multibagger_targets.py
- live_predictions/${TODAY}.json with cross-validated basket
$(if [ "$(date +%u)" = "7" ]; then echo "- Weekly: devils_advocate full audit + news A/B backtest"; fi)

Operating under CONSTITUTION.md (autonomous mode, no manual approval)." \
            >> "$LOG" 2>&1 \
        && git -c credential.helper=osxkeychain push >> "$LOG" 2>&1 \
        && log "<<< git: committed + pushed" \
        || log "<<< git: commit/push FAILED — check $LOG"
    fi
} 2>&1 | tee -a "$LOG"

log "============================================="
log "Daily refresh done — $(date)"
log "log: $LOG"
log "============================================="
