"""Build the bootstrap data snapshot — the minimal set a cloner needs to run the system.

Why: the repo is 11 MB of code; the data tree is 61 GB and gitignored. Without a
snapshot, a cloner faces a multi-day NSE backfill before anything runs. This packs
the ESSENTIAL ~1 GB (keystone price parquet + macro/events/corp-actions panels)
into one tar.gz for publishing as a GitHub Release asset (2 GB/file limit, free
bandwidth, no Git-LFS quota traps).

Everything NOT in the snapshot is either regenerated by the engines (data/ml/,
engine outputs) or backfilled incrementally by the fetchers from the snapshot's
date forward (cheap — days, not decades).

Usage:
  python3 src/agentic/make_data_snapshot.py            # writes tmp/data_snapshot_YYYY-MM-DD.tar.gz
  gh release create data-YYYY-MM-DD tmp/data_snapshot_*.tar.gz --title ... --notes ...

Cloner side: bootstrap_data.sh downloads + extracts + verifies.
Stdlib-only, per the simplicity policy.
"""
from __future__ import annotations
import hashlib
import json
import tarfile
from datetime import date
from pathlib import Path

ROOT = Path("/Users/abhinavs./Documents/Zoom")

# The minimal set that lets a clean clone pass the freshness gate structure and
# run the weekly pipeline with --skip-fetch, then catch up via incremental fetchers.
ESSENTIALS = [
    "data/derived/stock_daily_facts_adjusted_2015plus.parquet",  # keystone: 15yr adjusted prices+features
    "data/derived/macro_panel.parquet",
    "data/derived/industry_panel.parquet",
    "data/derived/news_event_features.parquet",
    "data/derived/global_rates.parquet",
    "data/derived/commodity_prices.parquet",
    "data/derived/macro_timeseries.parquet",
    "data/derived/missed_winner_classifier.parquet",
    "data/events_full_history/normalized/stock_announcements.parquet",
    "data/corporate_actions_full_history/_incremental/normalized/stock_corporate_actions.parquet",
]


def main() -> None:
    out = ROOT / f"tmp/data_snapshot_{date.today().isoformat()}.tar.gz"
    out.parent.mkdir(parents=True, exist_ok=True)

    manifest = {"created": date.today().isoformat(), "files": []}
    missing = [p for p in ESSENTIALS if not (ROOT / p).exists()]
    if missing:
        raise SystemExit(f"ABORT — missing essentials: {missing}")

    with tarfile.open(out, "w:gz", compresslevel=4) as tar:
        for rel in ESSENTIALS:
            fp = ROOT / rel
            digest = hashlib.sha256(fp.read_bytes()).hexdigest()
            manifest["files"].append({"path": rel, "bytes": fp.stat().st_size, "sha256": digest})
            tar.add(fp, arcname=rel)
            print(f"  + {rel}  ({fp.stat().st_size/1e6:.1f} MB)")
        mpath = ROOT / "tmp/snapshot_manifest.json"
        mpath.write_text(json.dumps(manifest, indent=1))
        tar.add(mpath, arcname="data/snapshot_manifest.json")

    print(f"\nwrote {out}  ({out.stat().st_size/1e9:.2f} GB)")
    print("publish: gh release create data-" + manifest["created"] +
          f" {out} --title 'Data snapshot {manifest['created']}' --notes-file <notes>")


if __name__ == "__main__":
    main()
